name: 02-Workflow-Event

on: 
    # push:
    # pull_request:
    workflow_dispatch:
    # schedule:
    #     - cron: '*/5 * * * *' # every 5 minutes

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: show the trigger
              run: echo "I've been triggered by ${{ github.event_name}} event"