name: 02-Workflow-Event

on: push

jobs:
    echo:
        runs-on: ubuntu-runner
        steps:
            - name: show the trigger
              run: echo "I've been triggered by $ {{ github.event_name}} event"