name: 04 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4 # custom action to checkout code from the repository

            - name: Setup Node
              uses: actions/setup-node@v4 # custom action to setup Node.js environment
              with:
                node-version: '20.x'

            - name: Install dependencies
              run: |
                cd using-actions/react-app
                npm ci 