name: 13 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: 'Whether to execute cache step'
        type: boolean
        default: true
      node-version:
        description: 'Select Node.js version to setup'
        type: choice
        options:
          - '26.x'
          - '20.x'
          - '18.x'
        default: '26.x'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ github.event.inputs.node-version }}
      - name: Download cached dependencies
        uses: actions/cache@v3
        if: ${{ github.event.inputs.use-cache }}
        id: cache
        with:
          path: 13-caching/react-app/node_modules
          key: dep-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Testing
        run: npm run test
      - name: Building
        run: npm run build
      - name: Deploy to nonprod
        run: echo "Deploying to nonprod"
